---
title: "Final Project"
author: "Diego Flores"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(dplyr)
library(ggthemes)
library(gganimate)
library(janitor)
library(reshape)
library(tidyr)
library(tidyverse)

gdp_percap <- read_csv("raw-data/UNdata_Export_20191204_070705114.zip",
                       col_types = cols(
  `Country or Area` = col_character(),
  Year = col_double(),
  Item = col_character(),
  Value = col_double()
)) %>% clean_names() %>% 
  rename(c("country_or_area" = "entity")) %>% 
  select(entity, year, value)

regime_type <- read_csv("raw-data/political-regime-updated2016.csv",
                        col_types = cols(
  Entity = col_character(),
  Code = col_character(),
  Year = col_double(),
  `Political Regime (OWID based on Polity IV and Wimmer & Min) (Score)` = col_double()
)) %>% 
  clean_names() %>% 
  rename(c("political_regime_owid_based_on_polity_iv_and_wimmer_min_score" = "score")) %>% 
  mutate(democracy = ifelse(score >= 6, 1, 0)) %>% 
  select(entity, year, score, democracy)

infant_mortality <- read_csv("raw-data/child-deaths-igme-data.csv", 
                             col_types = cols(
                               Entity = col_character(),
                               Code = col_character(),
                               Year = col_double(),
                               `Number of under-five deaths` = col_double()
                               )) %>% 
  clean_names() %>% 
  rename(c("number_of_under_five_deaths" = "rate")) %>% 
  select(entity, year, rate)

world_pop <- read_csv("raw-data/population.csv", 
                      col_types = cols(
                        Entity = col_character(),
                        Code = col_character(),
                        Year = col_double(),
                        Population = col_double()
                      )) %>% 
  clean_names() %>% 
  select(entity, year, population)
  

world_density <- read_csv("raw-data/population-density.csv",
                          col_types = cols(
                            Entity = col_character(),
                            Code = col_character(),
                            Year = col_double(),
                            `Population density (people per sq. km of land area) (people per km² of land area)` = col_double()
                          )) %>% 
  clean_names() %>% 
  rename(c("population_density_people_per_sq_km_of_land_area_people_per_km_of_land_area" = "density")) %>% 
  select(entity, year, density)

growth_democracy <- read_csv("raw-data/numbers-of-autocracies-and-democracies.csv",
                             col_types = cols(
                               Entity = col_character(),
                               Code = col_character(),
                               Year = col_double(),
                               Democracies = col_double(),
                               Autocracies = col_double()
                             )) %>% 
  clean_names %>% 
  select(year, democracies, autocracies)

life_expectancy <- read_csv("raw-data/life-expectancy.csv",
                            col_types = cols(
                              Entity = col_character(),
                              Code = col_character(),
                              Year = col_double(),
                              `Life expectancy (years)` = col_double()
                            )) %>% clean_names() %>% 
  rename(c("life_expectancy_years" = "expectancy")) %>% 
  select(entity, year, expectancy)

happiness_country <- read_csv("raw-data/happiness-cantril-ladder.csv",
                              col_types = cols(
                                Entity = col_character(),
                                Code = col_character(),
                                Year = col_double(),
                                `World Happiness Report 2016 (Cantril Ladder (0=worst; 10=best))` = col_double()
                              )) %>% 
  clean_names() %>% 
  rename(c("world_happiness_report_2016_cantril_ladder_0_worst_10_best" = "cantril_score")) %>% 
  select(entity, year, cantril_score)

hdi <- read_csv("raw-data/human-development-index.csv", 
                col_types = cols(
                  Entity = col_character(),
                  Code = col_character(),
                  Year = col_double(),
                  `((0-1; higher values are better))` = col_double()
                )) %>% 
  clean_names() %>% 
  rename(c("x0_1_higher_values_are_better" = "hdi")) %>% 
  select(entity, year, hdi)
```

```{r, this is where I merged the data}
hdi_happy <- merge(hdi,  happiness_country,
                   by = c("entity", "year"), 
                   all = TRUE)
hdi_happy_le <- merge(hdi_happy, life_expectancy,
                      by = c("entity", "year"), 
                      all = TRUE)
hdi_happy_le_d <- merge(hdi_happy_le,  world_density, 
                        by = c("entity", "year"), 
                        all = TRUE)
hdi_happy_le_d_p <- merge(hdi_happy_le_d, world_pop, 
                          by = c("entity", "year"), 
                          all = TRUE)
hdi_happy_le_d_p_im <- merge(hdi_happy_le_d_p, infant_mortality, 
                             by = c("entity", "year"), 
                             all = TRUE)
hdi_happy_le_d_p_im_rt <- merge(hdi_happy_le_d_p_im, regime_type, 
                                by = c("entity", "year"), 
                                all = TRUE)
full_data <- merge(hdi_happy_le_d_p_im_rt, gdp_percap, 
                   by = c("entity", "year"), 
                   all = TRUE)
```

```{r, growth of democracy graphs}

democracy_graph <- ggplot() + geom_line(data = growth_democracy, aes(x = year, y = democracies), color = "blue", show.legend = TRUE) + geom_line(data = growth_democracy, aes(x = year, y = autocracies), color = "red", show.legend = TRUE) + ggtitle("Rise of Democracy Throughout the World") + labs(x = "Year", y = "Number of Democracies/Autocracies") + theme_igray()


bar_graph <- regime_type %>% 
  filter(year == 1950) %>% 
  ggplot(aes(x = democracy, fill = democracy)) + 
  geom_bar() + 
  ggtitle("Number of Autocracies vs Democracies") + 
  labs(x = "Type of Government", 
       y = "Number of Countries") +
  scale_fill_brewer(direction = -1, palette = "Blues") +
  scale_x_discrete(limits = 2)

```


```{r, Graphs on Life Expectancy}
afghanistan_life <- life_expectancy %>% 
  filter(entity == "Afghanistan")
afghanistan_life_graph <- afghanistan_life %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("Afgani Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 1988, color = "blue")

sweden_le <- life_expectancy %>%
  filter(entity == "Sweden") %>% 
  filter(year > 1890)
sweden_le_graph <- sweden_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + ggtitle("Swedish Life Expectancy") +
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 1920, color = "blue")

indonesia_le <- life_expectancy %>% 
  filter(entity == "Indonesia") %>% 
  filter(year > 1960)
indonesia_le_graph <- indonesia_le %>% 
  ggplot(aes(x = year, y = expectancy)) +
  geom_line(color = "red") + ggtitle("Indonesian Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() +
  geom_vline(xintercept = 1999, color = "blue")


spain_le <-  life_expectancy %>% 
  filter(entity == "Spain")
spain_life_graph <- spain_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("Spanish Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 1978, color = "blue")

serbia_le <- life_expectancy %>% 
  filter(entity == "Serbia")
serbia_life_graph <- serbia_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("Serbian Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 2006, color = "blue")

albania_le <- life_expectancy %>% 
  filter(entity == "Albania")
albania_life_graph <- albania_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("Albanian Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 2002, color = "blue")
  

croatia_le <- life_expectancy %>% 
  filter(entity == "Croatia")
croatia_life_graph <- croatia_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("Croatian Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 2000, color = "blue")

slovenia_le <- life_expectancy %>% 
  filter(entity == "Slovenia")
slovenia_life_graph <- slovenia_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("Slovene Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 1991, color = "blue")

germany_le <- life_expectancy %>% 
  filter(entity == "Germany")
germany_life_graph <- germany_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("German Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 1990, color = "blue")

hungary_le <- life_expectancy %>% 
  filter(entity == "Hungary")
hungary_life_graph <- hungary_le %>% 
  ggplot(aes(x = year, y = expectancy)) + 
  geom_line(color = "red") + 
  ggtitle("Hungarian Life Expectancy") + 
  labs(x = "Year", y = "Expected Age of Death") + 
  theme_gray() + 
  geom_vline(xintercept = 1990, color = "blue")

```


```{r, graphs on gdp}
afghanistan_gdp <- gdp_percap %>% 
  filter(entity == "Afghanistan")
afghani_gdp_graph <- afghanistan_gdp %>% 
  ggplot(aes(x = year, y = value )) + 
  geom_line(color = "red") +
  ggtitle("Afghanistan GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 1988, color = "blue")

indonesia_gdp <- gdp_percap %>% 
  filter(entity == "Indonesia")
indonesia_gdp_graph <- indonesia_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle("Indonesian GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 1999, color = "blue")

spain_gdp <- gdp_percap %>% 
  filter(entity == "Spain")
spain_gdp_graph <- spain_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle("Spanish GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 1978, color = "blue")

slovenia_gdp <- gdp_percap %>% 
  filter(entity == "Slovenia")
slovenia_gdp_graph <- slovenia_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle(" GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 1991, color = "blue")

germany_gdp <- gdp_percap %>% 
  filter(entity == "Germany")
germany_gdp_graph <- germany_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle(" GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 1990, color = "blue")

croatia_gdp <- gdp_percap %>% 
  filter(entity == "Croatia")
croatia_gdp_graph <- croatia_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle(" GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 2000, color = "blue")

albania_gdp <- gdp_percap %>% 
  filter(entity == "Albania")
albania_gdp_graph <- albania_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle(" GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 2002, color = "blue")

hungary_gdp <- gdp_percap %>% 
  filter(entity == "Hungary")
hungary_gdp_graph <- hungary_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle(" GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 1990, color = "blue")

serbia_gdp <- gdp_percap %>% 
  filter(entity == "Serbia")
serbia_gdp_graph <- serbia_gdp %>% 
  ggplot(aes(x = year, y = value)) +
  geom_line(color = "red") +
  ggtitle(" GDP per Capita") +
  labs(x = "Year", y = "Value of GDP per Capita") +
  theme_gray() +
  geom_vline(xintercept = 2006, color = "blue")
```


```{r, let's do hdi}
afghanistan_hdi <- hdi %>% 
  filter(entity == "Afghanistan") 
afghan_hdi_graph <- afghanistan_hdi %>% 
  ggplot(aes(x = year, y = hdi)) +
  geom_line(color = "red") +
  ggtitle("Afghanistan HDI Rating over Time") +
  labs(x = "Year", y = "HDI Rating") +
  theme_gray() +
  geom_vline(xintercept = 1988, color = "blue")

indonesia_hdi <- hdi %>% 
  filter(entity == "Indonesia")
indonesia_hdi_graph <- indonesia_hdi %>% 
  ggplot(aes(x = year, y = hdi)) +
  geom_line(color = "red") +
  ggtitle("Indonesian HDI Rating over Time") +
  labs(x = "Year", y = "HDI Rating") +
  theme_gray() +
  geom_vline(xintercept = 1999, color = "blue")

albania_hdi <- hdi 
```

```{r, now we will do happiness}
tunisia_happiness <- happiness_country %>% 
  filter(entity == "Tunisia") 
tunisia_happiness_graph <- tunisia_happiness %>% 
  ggplot(aes(x = year, y = cantril_score)) +
  geom_line(color = "red") +
  ggtitle("Tunisian Happiness Over Time") +
  labs(x = "Year", y = "Cantril Scale Rating") +
  theme_gray() +
  geom_vline(xintercept = 2014, color = "blue")

nepal_happiness <- happiness_country %>% 
  filter(entity == "Nepal")
nepal_happiness_graph <- nepal_happiness %>% 
  ggplot(aes(x = year, y = cantril_score)) +
  geom_line(color = "red") +
  ggtitle("Nepalese Happiness Rating over Time") +
  labs(x = "Year", y = "Cantril Scale Score") +
  theme_gray() +
  geom_vline(xintercept = 2008, color = "blue")

```

```{r, infant mortality}
afghanistan_im <- infant_mortality %>% 
  filter(entity == "Afghanistan") 
afghanistan_im_graph <- afghanistan_im %>% 
  ggplot(aes(x = year, y = rate)) +
  geom_line(color = "red") +
  ggtitle("Afghanistan Infant Mortality Rate Over Time") +
  labs(x = "Year", y = "Number of Deaths Under Age 5") +
  theme_gray() +
  geom_vline(xintercept = 1988, color = "blue")

indonesia_im <- infant_mortality %>% 
  filter(entity == "Indonesia") %>% 
  filter(year > 1960)
indonesia_im_graph <- indonesia_im %>% 
  ggplot(aes(x = year, y = rate)) +
  geom_line(color = "red") + ggtitle("Indonesian Infant Mortality Rate Over Time") + 
  labs(x = "Year", y = "Number of Deaths Under Age 5") + 
  theme_gray() +
  geom_vline(xintercept = 1999, color = "blue")
```


```{r regression analysis}
full_data  %>% filter(year == 2010) %>% 
  ggplot(aes(x = democracy, y = value)) + geom_point() + 
  geom_jitter(height = 0.2, width = 0.2) +
  geom_smooth(method = "lm", se = FALSE) + 
  labs(y = "GDP per Capita", x = "Non-Democratic (0) or Democratic (1)") +
  ggtitle("GDP per Cap of Democratic vs Non-Democratic Countries")

full_data %>% filter(year == 2010) %>% 
      ggplot(aes(x = democracy, y = expectancy)) + geom_point() + 
      geom_jitter(height = 0.2, width = 0.2) +
      geom_smooth(method = "lm", se = FALSE)  + 
      labs(y = "Life Expectancy", x = "Non-Democratic (0) or Democratic (1)") +
      ggtitle("Life Expectancy of Democratic vs Non-Democratic Countries")

full_data %>% filter(year == 2010) %>% 
      ggplot(aes(x = democracy, y = hdi)) + geom_point() + 
      geom_jitter(height = 0.2, width = 0.2) +
      geom_smooth(method = "lm", se = FALSE)  + 
      labs(y = "HDI Score", x = "Non-Democratic (0) or Democratic (1)") +
      ggtitle("HDI of Democratic vs Non-Democratic Countries")

full_data %>% filter(year == 2010) %>% 
      ggplot(aes(x = democracy, y = cantril_score)) + geom_point() + 
      geom_jitter(height = 0.2, width = 0.2) +
      geom_smooth(method = "lm", se = FALSE)  + 
      labs(y = "Cantril Score", x = "Non-Democratic (0) or Democratic (1)") +
      ggtitle("Happiness of Democratic vs Non-Democratic Countries")


full_data %>% filter(year == 2010) %>% 
      ggplot(aes(x = democracy, y = rate)) + geom_point() + 
      geom_jitter(height = 0.2, width = 0.2) +
      geom_smooth(method = "lm", se = FALSE)  + 
  labs(y = "Value", x = "Non-Democratic (0) or Democratic (1)") +
      ggtitle("Infant Mortality Rates of Democratic vs Non-Democratic Countries")
```


